In [1]:
import sys
sys.path.append('C:\\Users\\DavidB\\PycharmProjects\\My_Football_Analytics\\Basics')

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from mplsoccer import Pitch
from Pitch.My_Pitch import \
    myPitch  # might need adaptation of path depending on whether it is used in pycharm or jupyter notebook
import matplotlib.image as mpimg
from matplotlib.offsetbox import TextArea, DrawingArea, OffsetImage, AnnotationBbox
import plotly.express as px
import plotly.graph_objects as go
from PIL import Image
import numpy as np

In [3]:
from Data.Statsbomb_Data import match_events

None

In [4]:
df, teams = match_events(match_id=3857261, event_filter='passes')

In [5]:
df

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,duration,related_events,pass,match_id,possession_team_id,team_id,player_id,under_pressure,off_camera,counterpress
0,285b3d0e-ed65-4f11-84ee-1ac2e6b0491e,5,1,00:00:00.371,0,0,Pass,2,Wales,From Kick Off,...,1.615000,[b7e37843-7498-42db-b117-ad4d40e0ed8c],"{'recipient': {'id': 3086, 'name': 'Ben Davies...",3857261,907,907,3517,NaN,NaN,NaN
1,cc3a9362-5f27-4b31-a11f-f776a3f12858,8,1,00:00:03.866,0,3,Pass,2,Wales,From Kick Off,...,2.742332,[916f2f17-c7ba-44b0-bce6-711b100f6d29],"{'length': 49.07311, 'angle': -0.16581869, 'he...",3857261,907,907,3086,NaN,NaN,NaN
2,916f2f17-c7ba-44b0-bce6-711b100f6d29,9,1,00:00:06.609,0,6,Pass,2,Wales,From Kick Off,...,2.893471,"[cc3a9362-5f27-4b31-a11f-f776a3f12858, dd4b8fa...","{'recipient': {'id': 4354, 'name': 'Philip Fod...",3857261,907,768,3943,NaN,NaN,NaN
3,544d2090-8f94-48d1-b78b-f3ffa62ba544,11,1,00:00:21.025,0,21,Pass,3,Wales,From Throw In,...,4.573407,"[88a6c333-6ec0-4019-98c7-d1109c3c14ef, 9c31f4d...","{'recipient': {'id': 3853, 'name': 'Kieffer Ro...",3857261,907,907,3086,NaN,NaN,NaN
4,88a6c333-6ec0-4019-98c7-d1109c3c14ef,14,1,00:00:25.598,0,25,Pass,3,Wales,From Throw In,...,4.625382,"[544d2090-8f94-48d1-b78b-f3ffa62ba544, b4c9473...","{'recipient': {'id': 10955, 'name': 'Harry Kan...",3857261,907,768,3244,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,ea1a4c69-03b0-4587-9d2b-0da7cf9e5c5a,3288,2,00:48:19.809,93,19,Pass,156,England,From Free Kick,...,0.416533,[c5919be5-1b37-438f-a378-eb91a0f42d6f],"{'recipient': {'id': 3616, 'name': 'Callum Wil...",3857261,768,768,9638,NaN,NaN,NaN
977,7e61deaa-1696-4b9d-82a7-f42879067605,3298,2,00:48:24.541,93,24,Pass,156,England,From Free Kick,...,0.796615,[9e0c67f4-ef33-4a0f-ad8b-b7df08b6dd66],"{'recipient': {'id': 4354, 'name': 'Philip Fod...",3857261,768,768,9638,NaN,NaN,NaN
978,259a1b8b-3ed8-4ed9-ba17-dd4baec49796,3305,2,00:48:27.239,93,27,Pass,156,England,From Free Kick,...,2.855230,NaN,"{'length': 33.672096, 'angle': -1.4696501, 'he...",3857261,768,907,4774,NaN,NaN,NaN
979,be72239d-9012-4b3d-9049-d7fae8227736,3306,2,00:48:55.723,93,55,Pass,157,England,From Throw In,...,1.672468,[069ae913-ee12-4380-88d9-e7ccdc0f62ac],"{'recipient': {'id': 9638, 'name': 'Jack Greal...",3857261,768,768,3664,NaN,NaN,NaN
980,359aa65d-c58b-4caf-abca-8609d499ed0e,3313,2,00:48:59.551,93,59,Pass,157,England,From Throw In,...,1.175440,[c31aab2d-a019-45fd-8578-50ad9b897442],"{'recipient': {'id': 3532, 'name': 'Jordan Bri...",3857261,768,768,9638,NaN,NaN,NaN

In [6]:
from Pass_Data import pass_data
passdata = pass_data(df, data_source='Statsbomb')
passdata

In [7]:
print(passdata)

pass_data object of Statsbomb of shape (981, 18).

In [8]:
passdata.data

,player,period,minute,second,team,outcome,type,x_initial,y_initial,x_received,y_received,cross,cut-back,switch,shot_assist,goal_assist,play_pattern,related_events
0,Aaron Ramsey,1,0,0,Wales,Complete,Kick Off,60.0,40.0,36.5,28.7,False,False,False,False,False,From Kick Off,[b7e37843-7498-42db-b117-ad4d40e0ed8c]
1,Ben Davies,1,0,3,Wales,Incomplete,Regular,41.8,26.0,90.2,17.9,False,False,False,False,False,From Kick Off,[916f2f17-c7ba-44b0-bce6-711b100f6d29]
2,Declan Rice,1,0,6,England,Out,Recovery,90.1,17.8,63.2,0.0,False,False,False,False,False,From Kick Off,"[cc3a9362-5f27-4b31-a11f-f776a3f12858, dd4b8fa..."
3,Ben Davies,1,0,21,Wales,Incomplete,Throw-in,63.9,0.1,99.7,5.4,False,False,False,False,False,From Throw In,"[88a6c333-6ec0-4019-98c7-d1109c3c14ef, 9c31f4d..."
4,John Stones,1,0,25,England,Out,Recovery,99.6,5.3,45.5,0.0,False,False,False,False,False,From Throw In,"[544d2090-8f94-48d1-b78b-f3ffa62ba544, b4c9473..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,Jack Grealish,2,93,19,England,Complete,Regular,12.8,29.6,11.6,34.7,False,False,False,False,False,From Free Kick,[c5919be5-1b37-438f-a378-eb91a0f42d6f]
977,Jack Grealish,2,93,24,England,Complete,Regular,8.3,32.3,9.0,31.5,False,False,False,True,False,From Free Kick,[9e0c67f4-ef33-4a0f-ad8b-b7df08b6dd66]
978,Connor Roberts,2,93,27,Wales,Out,Regular,3.2,33.6,6.6,0.1,False,False,False,False,False,From Free Kick,NaN
979,Trent Alexander-Arnold,2,93,55,England,Complete,Throw-in,6.5,0.0,16.1,22.8,False,False,False,False,False,From Throw In,[069ae913-ee12-4380-88d9-e7ccdc0f62ac]
980,Jack Grealish,2,93,59,England,Complete,Regular,12.2,13.4,22.1,5.9,False,False,False,False,False,From Throw In,[c31aab2d-a019-45fd-8578-50ad9b897442]

In [17]:
passdata.get_passes(get='From Free Kick')

(                     player  period  minute  second     team     outcome  \
 79             Chris Mepham       1       5      27    Wales    Complete
 80                Joe Allen       1       5      29    Wales    Complete
 81                Joe Rodon       1       5      32    Wales    Complete
 82               Ben Davies       1       5      34    Wales    Complete
 83               Danny Ward       1       5      38    Wales  Incomplete
 ..                      ...     ...     ...     ...      ...         ...
 974           Jack Grealish       2      93      14  England    Complete
 975  Jordan Brian Henderson       2      93      15  England    Complete
 976           Jack Grealish       2      93      19  England    Complete
 977           Jack Grealish       2      93      24  England    Complete
 978          Connor Roberts       2      93      27    Wales         Out

           type  x_initial  y_initial  x_received  y_received  cross  cut-back  \
 79   Free Kick       42.4       58.4        47.6        52.1  False     False
 80     Regular       47.0       52.1        37.6        36.0  False     False
 81     Regular       39.5       34.6        38.3        13.4  False     False
 82     Regular       35.9       16.3         9.4        37.1  False     False
 83     Regular        7.1       39.6        52.2        57.8  False     False
 ..         ...        ...        ...         ...         ...    ...       ...
 974    Regular       45.6       44.8        39.9        44.0  False     False
 975    Regular       37.8       43.0        38.7        37.9  False     False
 976    Regular       12.8       29.6        11.6        34.7  False     False
 977    Regular        8.3       32.3         9.0        31.5  False     False
 978    Regular        3.2       33.6         6.6         0.1  False     False

      switch  shot_assist  goal_assist    play_pattern  \
 79    False        False        False  From Free Kick
 80    False        False        False  From Free Kick
 81    False        False        False  From Free Kick
 82    False        False        False  From Free Kick
 83    False        False        False  From Free Kick
 ..      ...          ...          ...             ...
 974   False        False        False  From Free Kick
 975   False        False        False  From Free Kick
 976   False        False        False  From Free Kick
 977   False         True        False  From Free Kick
 978   False        False        False  From Free Kick

                              related_events
 79   [2afbe4d4-f6ec-4871-b46e-daec2a98c331]
 80   [053f380a-ee31-4da7-ae3f-ce3f28d82aa4]
 81   [3e4a48ec-ca1f-4429-901e-6e08b376bf03]
 82   [4b45d20b-07e1-49e2-998c-376acf18481a]
 83   [4d885a6f-c200-433c-abc5-c098c172bd41]
 ..                                      ...
 974  [e8d497ac-5442-421b-b858-163823f7f07b]
 975  [a51c9035-edee-4e2f-9972-5d6893455952]
 976  [c5919be5-1b37-438f-a378-eb91a0f42d6f]
 977  [9e0c67f4-ef33-4a0f-ad8b-b7df08b6dd66]
 978                                     NaN

 [205 rows x 18 columns],
 {'Wales': 51, 'England': 154})