https://www.youtube.com/watch?v=8TrleFklEsE

In [1]:
import sys
sys.path.append('C:\\Users\\DavidB\\PycharmProjects\\My_Football_Analytics\\Basics')

import pandas as pd
import numpy as np
import Data.Metrica_IO as mio
import Pitch.Metrica_Pitch as mp
import matplotlib.pyplot as plt

In [2]:
data_dir = 'sample-data-master/data/'
game_id = 2
away = mio.tracking_data(DATADIR=data_dir, game_id=game_id, teamname='Away')
home = mio.tracking_data(DATADIR=data_dir, game_id=game_id, teamname='Home')

Reading team: away
Reading team: home

In [3]:
td = mio.merge_tracking_data(home, away)
td

,Period_x,Time [s]_x,Home_11_x,Home_11_y,Home_1_x,Home_1_y,Home_2_x,Home_2_y,Home_3_x,Home_3_y,...,Away_22_x,Away_22_y,Away_23_x,Away_23_y,Away_24_x,Away_24_y,Away_26_x,Away_26_y,ball_x,ball_y
Frame,,,,,,,,,,,,,,,,,,,,,
1,1,0.04,0.94275,0.50413,0.64812,0.28605,0.67752,0.42803,0.69882,0.55606,...,0.49889,-0.02263,0.50177,0.50145,0.49517,0.36234,NaN,NaN,NaN,NaN
2,1,0.08,0.94275,0.50413,0.64812,0.28605,0.67752,0.42803,0.69882,0.55606,...,0.49889,-0.02263,0.50177,0.50145,0.49517,0.36234,NaN,NaN,NaN,NaN
3,1,0.12,0.94275,0.50413,0.64812,0.28605,0.67752,0.42803,0.69882,0.55606,...,0.49889,-0.02263,0.50177,0.50145,0.49517,0.36234,NaN,NaN,NaN,NaN
4,1,0.16,0.94275,0.50413,0.64812,0.28605,0.67752,0.42803,0.69882,0.55606,...,0.49889,-0.02263,0.50177,0.50145,0.49517,0.36234,NaN,NaN,NaN,NaN
5,1,0.20,0.94275,0.50413,0.64812,0.28605,0.67752,0.42803,0.69882,0.55606,...,0.49889,-0.02263,0.50177,0.50145,0.49517,0.36234,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141152,2,5646.08,0.06285,0.51243,0.38499,0.15356,0.22558,0.41355,0.27142,0.32209,...,NaN,NaN,0.26855,0.61845,0.36760,0.12496,0.44966,0.41572,NaN,NaN
141153,2,5646.12,0.06285,0.51243,0.38499,0.15356,0.22558,0.41355,0.27142,0.32209,...,NaN,NaN,0.26855,0.61845,0.36760,0.12496,0.44983,0.41550,NaN,NaN
141154,2,5646.16,0.06285,0.51243,0.38499,0.15356,0.22558,0.41355,0.27142,0.32209,...,NaN,NaN,0.26855,0.61845,0.36760,0.12496,0.44997,0.41485,NaN,NaN
141155,2,5646.20,0.06285,0.51243,0.38499,0.15356,0.22558,0.41355,0.27142,0.32209,...,NaN,NaN,0.26855,0.61845,0.36760,0.12496,0.45017,0.41515,NaN,NaN
141156,2,5646.24,0.06285,0.51243,0.38499,0.15356,0.22558,0.41355,0.27142,0.32209,...,NaN,NaN,0.26855,0.61845,0.36760,0.12496,0.45029,0.41545,NaN,NaN

In [ ]:
td_object = tracking