# Statsbomb data

Statsbom supplies us with loads of free Data and even provides a easy way to access it via their own package for python and R! <br>
https://github.com/statsbomb/statsbombpy <br>

In [1]:
from statsbombpy import sb

In [2]:
# filter for free data 
comps = sb.competitions()
comps = comps[~comps['match_available_360'].isnull()]
comps

C:\Users\DavidB\PycharmProjects\My_Football_Analytics\Football_Analytics_venv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
26,43,106,International,FIFA World Cup,male,False,True,2022,2023-08-12T16:44:27.619465,2023-08-17T15:55:15.164685,2023-08-17T15:55:15.164685,2023-08-12T16:44:27.619465
35,11,90,Spain,La Liga,male,False,False,2020/2021,2023-07-26T14:11:01.312143,2023-07-26T14:15:15.217027,2023-07-26T14:15:15.217027,2023-07-26T14:11:01.312143
62,55,43,Europe,UEFA Euro,male,False,True,2020,2023-02-24T21:26:47.128979,2023-04-27T22:38:34.970148,2023-04-27T22:38:34.970148,2023-02-24T21:26:47.128979
64,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2023-07-17T21:19:03.032991,2023-07-17T21:21:56.497106,2023-07-17T21:21:56.497106,2023-07-17T21:19:03.032991
65,72,107,International,Women's World Cup,female,False,True,2023,2023-09-01T12:34:19.705316,2023-09-01T12:35:45.762196,2023-09-01T12:35:45.762196,2023-09-01T12:34:19.705316

In [3]:
# All matches in a competition
sb.matches(competition_id=43, season_id=106)

C:\Users\DavidB\PycharmProjects\My_Football_Analytics\Football_Analytics_venv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3857256,2022-12-02,21:00:00.000,International - FIFA World Cup,2022,Serbia,Switzerland,2,3,available,...,2023-04-26T23:49:58.956186,3,Group Stage,Stadium 974,Fernando Andrés Rapallini,Dragan Stojković,Murat Yakin,1.1.0,2,2
1,3869151,2022-12-03,21:00:00.000,International - FIFA World Cup,2022,Argentina,Australia,2,1,available,...,2023-07-30T07:48:51.865595,4,Round of 16,Ahmad bin Ali Stadium,Szymon Marciniak,Lionel Sebastián Scaloni,Graham James Arnold,1.1.0,2,2
2,3857257,2022-11-30,17:00:00.000,International - FIFA World Cup,2022,Australia,Denmark,1,0,available,...,2023-06-20T11:04:37.638969,3,Group Stage,Al Janoub Stadium,Mustapha Ghorbal,Graham James Arnold,Kasper Hjulmand,1.1.0,2,2
3,3857258,2022-11-24,21:00:00.000,International - FIFA World Cup,2022,Brazil,Serbia,2,0,available,...,2023-07-11T14:56:31.096588,1,Group Stage,Lusail Stadium,Alireza Faghani,Telê Santana da Silva,Dragan Stojković,1.1.0,2,2
4,3857288,2022-11-26,12:00:00.000,International - FIFA World Cup,2022,Tunisia,Australia,0,1,available,...,2023-04-27T00:30:07.835815,2,Group Stage,Al Janoub Stadium,Daniel Siebert,Jalel Kadri,Graham James Arnold,1.1.0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,3857265,2022-11-22,18:00:00.000,International - FIFA World Cup,2022,Mexico,Poland,0,0,available,...,2023-04-27T00:49:30.005344,1,Group Stage,Stadium 974,Chris Beath,Gerardo Daniel Martino,Czesław Michniewicz,1.1.0,2,2
60,3857262,2022-12-02,17:00:00.000,International - FIFA World Cup,2022,South Korea,Portugal,2,1,available,...,2023-04-26T23:48:08.999798,3,Group Stage,Education City Stadium,Facundo Tello Figueroa,Paulo Jorge Gomes Bento,Fernando Manuel Fernandes da Costa Santos,1.1.0,2,2
61,3857261,2022-11-29,21:00:00.000,International - FIFA World Cup,2022,Wales,England,0,3,available,...,2023-04-27T00:02:44.241621,3,Group Stage,Ahmad bin Ali Stadium,Slavko Vinčić,Robert Page,Gareth Southgate,1.1.0,2,2
62,3857255,2022-12-01,21:00:00.000,International - FIFA World Cup,2022,Japan,Spain,2,1,available,...,2023-04-26T23:51:48.352990,3,Group Stage,Sheikh Khalifa International Stadium,Victor Miguel de Freitas Gomes,Hajime Moriyasu,Luis Enrique Martínez García,1.1.0,2,2
63,3857254,2022-11-22,15:00:00.000,International - FIFA World Cup,2022,Denmark,Tunisia,0,0,available,...,2023-07-29T19:44:56.738444,1,Group Stage,Education City Stadium,César Arturo Ramos Palazuelos,Kasper Hjulmand,Jalel Kadri,1.1.0,2,2

In [4]:
# event data for a specific match 
events = sb.events(match_id=3857261)

events

C:\Users\DavidB\PycharmProjects\My_Football_Analytics\Football_Analytics_venv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,50_50,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,block_deflection,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,...,shot_technique,shot_type,substitution_outcome,substitution_replacement,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4231, 'lineup': [{'player': {'id...",Wales,907,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 433, 'lineup': [{'player': {'id'...",England,768,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Wales,907,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,England,768,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Wales,907,00:00:00.000,Half Start,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Wales,907,00:49:00.329,Half End,NaN
3312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 433, 'lineup': [{'player': {'id'...",England,768,00:00:00.000,Tactical Shift,NaN
3313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4231, 'lineup': [{'player': {'id...",Wales,907,00:14:01.615,Tactical Shift,NaN
3314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 433, 'lineup': [{'player': {'id'...",England,768,00:33:32.963,Tactical Shift,NaN
3315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Wales,907,00:05:49.021,Error,NaN

In [5]:
# one event type
passes = sb.events(match_id=3857261, split=True, flatten_attrs=False)["passes"]
passes

C:\Users\DavidB\PycharmProjects\My_Football_Analytics\Football_Analytics_venv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,duration,related_events,pass,match_id,possession_team_id,team_id,player_id,under_pressure,off_camera,counterpress
0,285b3d0e-ed65-4f11-84ee-1ac2e6b0491e,5,1,00:00:00.371,0,0,Pass,2,Wales,From Kick Off,...,1.615000,[b7e37843-7498-42db-b117-ad4d40e0ed8c],"{'recipient': {'id': 3086, 'name': 'Ben Davies...",3857261,907,907,3517,NaN,NaN,NaN
1,cc3a9362-5f27-4b31-a11f-f776a3f12858,8,1,00:00:03.866,0,3,Pass,2,Wales,From Kick Off,...,2.742332,[916f2f17-c7ba-44b0-bce6-711b100f6d29],"{'length': 49.07311, 'angle': -0.16581869, 'he...",3857261,907,907,3086,NaN,NaN,NaN
2,916f2f17-c7ba-44b0-bce6-711b100f6d29,9,1,00:00:06.609,0,6,Pass,2,Wales,From Kick Off,...,2.893471,"[cc3a9362-5f27-4b31-a11f-f776a3f12858, dd4b8fa...","{'recipient': {'id': 4354, 'name': 'Philip Fod...",3857261,907,768,3943,NaN,NaN,NaN
3,544d2090-8f94-48d1-b78b-f3ffa62ba544,11,1,00:00:21.025,0,21,Pass,3,Wales,From Throw In,...,4.573407,"[88a6c333-6ec0-4019-98c7-d1109c3c14ef, 9c31f4d...","{'recipient': {'id': 3853, 'name': 'Kieffer Ro...",3857261,907,907,3086,NaN,NaN,NaN
4,88a6c333-6ec0-4019-98c7-d1109c3c14ef,14,1,00:00:25.598,0,25,Pass,3,Wales,From Throw In,...,4.625382,"[544d2090-8f94-48d1-b78b-f3ffa62ba544, b4c9473...","{'recipient': {'id': 10955, 'name': 'Harry Kan...",3857261,907,768,3244,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,ea1a4c69-03b0-4587-9d2b-0da7cf9e5c5a,3288,2,00:48:19.809,93,19,Pass,156,England,From Free Kick,...,0.416533,[c5919be5-1b37-438f-a378-eb91a0f42d6f],"{'recipient': {'id': 3616, 'name': 'Callum Wil...",3857261,768,768,9638,NaN,NaN,NaN
977,7e61deaa-1696-4b9d-82a7-f42879067605,3298,2,00:48:24.541,93,24,Pass,156,England,From Free Kick,...,0.796615,[9e0c67f4-ef33-4a0f-ad8b-b7df08b6dd66],"{'recipient': {'id': 4354, 'name': 'Philip Fod...",3857261,768,768,9638,NaN,NaN,NaN
978,259a1b8b-3ed8-4ed9-ba17-dd4baec49796,3305,2,00:48:27.239,93,27,Pass,156,England,From Free Kick,...,2.855230,NaN,"{'length': 33.672096, 'angle': -1.4696501, 'he...",3857261,768,907,4774,NaN,NaN,NaN
979,be72239d-9012-4b3d-9049-d7fae8227736,3306,2,00:48:55.723,93,55,Pass,157,England,From Throw In,...,1.672468,[069ae913-ee12-4380-88d9-e7ccdc0f62ac],"{'recipient': {'id': 9638, 'name': 'Jack Greal...",3857261,768,768,3664,NaN,NaN,NaN
980,359aa65d-c58b-4caf-abca-8609d499ed0e,3313,2,00:48:59.551,93,59,Pass,157,England,From Throw In,...,1.175440,[c31aab2d-a019-45fd-8578-50ad9b897442],"{'recipient': {'id': 3532, 'name': 'Jordan Bri...",3857261,768,768,9638,NaN,NaN,NaN

In [6]:
passes.columns

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type',
       'possession', 'possession_team', 'play_pattern', 'team', 'player',
       'position', 'location', 'duration', 'related_events', 'pass',
       'match_id', 'possession_team_id', 'team_id', 'player_id',
       'under_pressure', 'off_camera', 'counterpress'],
      dtype='object')

In [7]:
passes.location

0       [60.0, 40.0]
1       [41.8, 26.0]
2       [29.9, 62.2]
3        [63.9, 0.1]
4       [20.4, 74.7]
           ...
976    [107.2, 50.4]
977    [111.7, 47.7]
978      [3.2, 33.6]
979    [113.5, 80.0]
980    [107.8, 66.6]
Name: location, Length: 981, dtype: object

In [8]:
passes['pass'][1]

{'length': 49.07311,
 'angle': -0.16581869,
 'height': {'id': 3, 'name': 'High Pass'},
 'end_location': [90.2, 17.9],
 'body_part': {'id': 38, 'name': 'Left Foot'},
 'outcome': {'id': 9, 'name': 'Incomplete'}}

In [9]:
events = sb.competition_events(
    country="International",
    division= "FIFA World Cup",
    season="2022",
    gender="male")

grouped_events = sb.competition_events(
    country="International",
    division= "FIFA World Cup",
    season="2022",
    split=True
)

C:\Users\DavidB\PycharmProjects\My_Football_Analytics\Football_Analytics_venv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\DavidB\PycharmProjects\My_Football_Analytics\Football_Analytics_venv\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [10]:
events

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,block_deflection,block_offensive,block_save_block,carry_end_location,clearance_aerial_won,...,shot_technique,shot_type,substitution_outcome,substitution_replacement,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 3412, 'lineup': [{'player': {'id...",Serbia,786,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4231, 'lineup': [{'player': {'id...",Switzerland,773,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 433, 'lineup': [{'player': {'id'...",Argentina,779,00:00:00.000,Starting XI,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 442, 'lineup': [{'player': {'id'...",Australia,792,00:00:00.000,Starting XI,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 442, 'lineup': [{'player': {'id'...",Australia,792,00:00:00.000,Starting XI,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,France,771,00:52:47.797,Offside,NaN
234648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Ecuador,3565,00:47:49.561,Offside,NaN
234649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Canada,1833,00:12:55.720,Offside,NaN
234650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Mexico,794,00:14:21.395,Offside,NaN
234651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,South Korea,791,00:16:10.656,Offside,NaN

In [11]:
grouped_events['shots']

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,shot_one_on_one,shot_deflected,under_pressure,shot_open_goal,shot_aerial_won,out,shot_follows_dribble,shot_saved_to_post,shot_saved_off_target,shot_redirect
0,61d52e72-a8ff-49c4-be02-057b1ea0fb15,20,1,00:00:18.696,0,18,Shot,2,Switzerland,From Kick Off,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,aa77495b-0e7b-44f0-a2eb-11605085943a,25,1,00:00:22.129,0,22,Shot,2,Switzerland,From Kick Off,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,51026369-a4ad-4a71-b14a-6e7f8b764772,28,1,00:00:23.845,0,23,Shot,2,Switzerland,From Kick Off,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6ac240f5-8b84-4c06-8153-b56109c8c5e6,196,1,00:04:35.297,4,35,Shot,11,Serbia,From Corner,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00e599c0-5234-4b6a-9b91-d6f789a311b0,356,1,00:10:05.636,10,5,Shot,24,Serbia,Regular Play,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1489,f49396ca-5d50-4662-9f55-6d2a87bfacfd,2846,2,00:24:16.276,69,16,Shot,137,Denmark,From Corner,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1490,a0ccad21-8e44-4a4f-ad5e-0eae6a6fcbc2,3077,2,00:30:27.456,75,27,Shot,151,Denmark,Regular Play,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1491,54778e9f-91a2-49da-912b-d6a68d9d8185,3570,2,00:46:09.522,91,9,Shot,182,Denmark,From Throw In,...,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN
1492,0cb9d4b2-e1ec-403f-99bf-ba2411c0e7e6,3601,2,00:46:41.468,91,41,Shot,185,Denmark,Regular Play,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1493,0d90f23c-4ee0-49bb-80e3-4be47400729c,3667,2,00:51:18.428,96,18,Shot,191,Denmark,From Corner,...,NaN,NaN,True,NaN,True,NaN,NaN,NaN,NaN,NaN