In [1]:
import pandas as pd
import numpy as np
from EventData import event_data

In [2]:
def load_event_data(datadir, fname):

    eventfile = datadir + '/' + fname
    print(eventfile)
    events = pd.read_csv(eventfile) # read data
    return events

In [3]:
ed = load_event_data('sample-data-master/data/Sample_Game_2', 'Sample_Game_2_RawEventsData.csv')
ed

sample-data-master/data/Sample_Game_2/Sample_Game_2_RawEventsData.csv

,Team,Type,Subtype,Period,Start Frame,Start Time [s],End Frame,End Time [s],From,To,Start X,Start Y,End X,End Y
0,Away,SET PIECE,KICK OFF,1,51,2.04,51,2.04,Player23,NaN,NaN,NaN,NaN,NaN
1,Away,PASS,NaN,1,51,2.04,87,3.48,Player23,Player20,0.50,0.50,0.40,0.51
2,Away,PASS,NaN,1,146,5.84,186,7.44,Player20,Player18,0.43,0.50,0.44,0.22
3,Away,PASS,NaN,1,248,9.92,283,11.32,Player18,Player17,0.47,0.19,0.31,0.28
4,Away,PASS,NaN,1,316,12.64,346,13.84,Player17,Player16,0.29,0.32,0.26,0.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1930,Away,BALL LOST,INTERCEPTION,2,140122,5604.88,140183,5607.32,Player21,NaN,0.54,0.77,0.29,0.24
1931,Home,CHALLENGE,AERIAL-LOST,2,140180,5607.20,140180,5607.20,Player1,NaN,0.31,0.30,NaN,NaN
1932,Away,CHALLENGE,AERIAL-LOST,2,140183,5607.32,140183,5607.32,Player24,NaN,0.32,0.30,NaN,NaN
1933,Home,RECOVERY,NaN,2,140211,5608.44,140211,5608.44,Player12,NaN,0.34,0.32,NaN,NaN
1934,Home,BALL OUT,CLEARANCE,2,140265,5610.60,140298,5611.92,Player12,NaN,0.33,0.16,0.41,-0.04

In [4]:
ED = event_data(data=ed, data_source='metrica', mirror_second_half=True)

In [5]:
print(ED)
ED.dimensions

event_data object with data from metrica

{'x': {'data': (0, 1),
  'pitch': (0, 105),
  'delta_data': 1,
  'delta_pitch': 105,
  'scaling_factor': 105.0},
 'y': {'data': (1, 0),
  'pitch': (0, 68),
  'delta_data': -1,
  'delta_pitch': 68,
  'scaling_factor': -68.0}}

In [6]:
ED.data

,Team,Type,Subtype,Period,Start_Frame,Start_Time_[s],End_Frame,End_Time_[s],Player,Receiver,Start_x,Start_y,End_x,End_y
0,Away,SET PIECE,KICK OFF,1,51,2.04,51,2.04,Player23,NaN,NaN,NaN,NaN,NaN
1,Away,PASS,NaN,1,51,2.04,87,3.48,Player23,Player20,52.50,34.00,42.00,33.32
2,Away,PASS,NaN,1,146,5.84,186,7.44,Player20,Player18,45.15,34.00,46.20,53.04
3,Away,PASS,NaN,1,248,9.92,283,11.32,Player18,Player17,49.35,55.08,32.55,48.96
4,Away,PASS,NaN,1,316,12.64,346,13.84,Player17,Player16,30.45,46.24,27.30,28.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1930,Away,BALL LOST,INTERCEPTION,2,140122,5604.88,140183,5607.32,Player21,NaN,48.30,52.36,74.55,16.32
1931,Home,CHALLENGE,AERIAL-LOST,2,140180,5607.20,140180,5607.20,Player1,NaN,72.45,20.40,NaN,NaN
1932,Away,CHALLENGE,AERIAL-LOST,2,140183,5607.32,140183,5607.32,Player24,NaN,71.40,20.40,NaN,NaN
1933,Home,RECOVERY,NaN,2,140211,5608.44,140211,5608.44,Player12,NaN,69.30,21.76,NaN,NaN
1934,Home,BALL OUT,CLEARANCE,2,140265,5610.60,140298,5611.92,Player12,NaN,70.35,10.88,61.95,-2.72

In [7]:
ED.get_event_by_type('SHOT')

,Team,Type,Subtype,Period,Start_Frame,Start_Time_[s],End_Frame,End_Time_[s],Player,Receiver,Start_x,Start_y,End_x,End_y
83,Home,SHOT,OFF TARGET-OUT,1,4419,176.76,4443,177.72,Player5,NaN,13.65,52.36,-2.10,36.72
198,Home,SHOT,ON TARGET-GOAL,1,12202,488.08,12212,488.48,Player10,NaN,5.25,30.60,-1.05,31.96
252,Home,SHOT,ON TARGET-SAVED,1,16484,659.36,16499,659.96,Player10,NaN,11.55,45.56,4.20,34.68
297,Away,SHOT,BLOCKED,1,18515,740.60,18520,740.80,Player22,NaN,84.00,44.20,90.30,45.56
431,Home,SHOT,HEAD-OFF TARGET-OUT,1,27345,1093.80,27360,1094.40,Player3,NaN,9.45,27.88,-1.05,27.88
472,Home,SHOT,ON TARGET-SAVED,1,29754,1190.16,29777,1191.08,Player4,NaN,21.00,20.40,0.00,31.28
823,Away,SHOT,ON TARGET-GOAL,1,53049,2121.96,53075,2123.00,Player24,NaN,96.60,36.72,106.05,35.36
852,Home,SHOT,HEAD-OFF TARGET-OUT,1,56079,2243.16,56131,2245.24,Player5,NaN,10.50,40.12,-2.10,16.32
962,Away,SHOT,OFF TARGET-HEAD-OUT,1,63362,2534.48,63372,2534.88,Player23,NaN,97.65,34.68,106.05,27.20
980,Away,SHOT,ON TARGET-SAVED,1,64772,2590.88,64799,2591.96,Player20,NaN,80.85,30.60,103.95,31.96
1026,Home,SHOT,OFF TARGET-OUT,1,67067,2682.68,67107,2684.28,Player7,NaN,13.65,15.64,-2.10,40.12
1058,Away,SHOT,OFF TARGET-OUT,2,69887,2795.48,69927,2797.08,Player21,NaN,82.95,44.88,108.15,25.84
1118,Home,SHOT,HEAD-ON TARGET-GOAL,2,73983,2959.32,73995,2959.80,Player9,NaN,5.25,35.36,-1.05,36.04
1277,Away,SHOT,OFF TARGET-OUT,2,86191,3447.64,86219,3448.76,Player19,NaN,85.05,36.72,107.10,40.12
1335,Away,SHOT,ON TARGET-SAVED,2,90165,3606.60,90176,3607.04,Player19,NaN,98.70,22.44,103.95,31.28
1479,Home,SHOT,ON TARGET-SAVED,2,98880,3955.20,98896,3955.84,Player10,NaN,4.20,29.92,1.05,30.60
1666,Away,SHOT,BLOCKED,2,111758,4470.32,111763,4470.52,Player24,NaN,95.55,26.52,98.70,30.60
1671,Away,SHOT,ON TARGET-GOAL,2,115009,4600.36,115024,4600.96,Player20,NaN,92.40,35.36,107.10,36.72
1681,Home,SHOT,HEAD-OFF TARGET-OUT,2,117218,4688.72,117245,4689.80,Player9,NaN,11.55,41.48,-1.05,28.56
1723,Home,SHOT,ON TARGET-GOAL,2,121027,4841.08,121055,4842.20,Player12,NaN,22.05,39.44,-1.05,36.72
1756,Home,SHOT,HEAD-OFF TARGET-OUT,2,124336,4973.44,124365,4974.60,Player9,NaN,7.35,34.00,-2.10,41.48
1843,Away,SHOT,OFF TARGET-OUT,2,132570,5302.80,132597,5303.88,Player18,NaN,86.10,25.84,109.20,31.96
1903,Away,SHOT,HEAD-OFF TARGET-OUT,2,136060,5442.40,136078,5443.12,Player 26,NaN,99.75,31.28,108.15,27.88
1927,Home,SHOT,ON TARGET-SAVED,2,139891,5595.64,139925,5597.00,Player9,NaN,31.50,35.36,2.10,35.36

In [8]:
ED.data.iloc[1334]

Team                  Away
Type                  PASS
Subtype                NaN
Period                   2
Start_Frame          90135
Start_Time_[s]      3605.4
End_Frame            90165
End_Time_[s]        3606.6
Player            Player24
Receiver          Player19
Start_x              87.15
Start_y              19.04
End_x                 98.7
End_y                22.44
Name: 1334, dtype: object